### ISSUE TITLE
Support for Triple Quoted Strings

### ISSUE THREAD

**Issue by codeviking** [jroesch/language-scala#22] opened 2015-05-05 21:48 UTC
The package doesn't support strings surrounded by triple `"`.

**Comment by gangstead** [comment] 2015-06-05 16:28
Seems to be working for me as of `v1.1.3`.  I suspect it was fixed by the deprecation update PR from @cjwilburn and others.

![image](https://cloud.githubusercontent.com/assets/527760/8010459/f66a12d4-0b75-11e5-8d59-7a5e56c1fcd6.png)

**Closed by gangstead** 2015-06-05 16:28 UTC

**Comment by codeviking** [comment] 2015-06-05 16:38
You're right.  What's weird is the Atom GUI for installing packages listed `1.0.0` as the latest version.  I used `apm` to reinstall the package and got the latest... thx!

**Comment by gangstead** [comment] 2015-06-05 17:49
I've had that happen as well when developing packages.  I go to check for updates and it doesn't show what I know is the latest version.  Someday I'll figure out how to make it reproducible and create an issue with Atom.
